### ISSUE TITLE
Alpine里编译musl test-case

### ISSUE THREAD

**Issue by GCYYfun** [GCYYfun/DailySchedule#1]
下载 Alpine 在 virtual box里安装、安装成功后
* 安装 过程 参考的官方文档 记录在  
 https://github.com/GCYYfun/DailySchedule/blob/master/zcore%20syscall%20detail.md
启动 后 应该是这个界面
![alpine启动后](https://user-images.githubusercontent.com/13977073/82641380-d691b480-9c3e-11ea-8f8f-9c0366b3de85.png)

安装需要的包：
apk add git
apk add make
apk add gcc
apk add libc-dev

下载 libc-test

> git clone git://repo.or.cz/libc-test

![git libc-test仓库](https://user-images.githubusercontent.com/13977073/82642622-caa6f200-9c40-11ea-9443-9fddb06eb5b7.png)

下载中

![下载中](https://user-images.githubusercontent.com/13977073/82642694-e7432a00-9c40-11ea-886b-f1159f9e7428.png)

下载完成 

![下载完成并ls](https://user-images.githubusercontent.com/13977073/82642832-1e194000-9c41-11ea-81c9-b9e9ed9faf36.png)

然后 进入 libc-test

> cd libc-test

![进入libc-test并ls](https://user-images.githubusercontent.com/13977073/82642856-296c6b80-9c41-11ea-8ddb-4431089298ef.png)

参考 README里
```
build and run tests:
	make
```
直接执行 make 
> make

make 后 经过很长的时间 、遇到些问题

如图：
![编译testcase](https://user-images.githubusercontent.com/13977073/82558707-d2af5500-9ba0-11ea-9d7f-d0c26b2c8660.png)

**Comment by function2-llx** [comment]
这好像就是成功了的意思？下面给出了失败的测例。有些文件编译失败貌似是整成的，比如我们也编不过 unistd。

**Comment by GCYYfun** [comment]
> 这好像就是成功了的意思？下面给出了失败的测例。有些文件编译失败貌似是整成的，比如我们也编不过 unistd。

好的、很有帮助、那我在看看、接下来怎么弄、

**Comment by chyyuu** [comment]
我已经在virtbox中安装了alpine liux，但我没法参考你的issue 编译 testcase和重现fail的情况。因为没有相关操作，你能补上吗？ 写issues的一个基本原则是让别人能够根据你的issues重现问题。

**Comment by chyyuu** [comment]
很好，改的很快！基于你新的信息，我重现了你的工作，得到类似的结果。

localhost:~/libc-test# make |grep FAIL|wc
       12        50       597
localhost:~/libc-test# 

这说明有12个test没有通过，出错了，具体显示内容与你的信息一致。

localhost:~/libc-test/src# find . -name "*.exe"|wc
      475       475     12829
localhost:~/libc-test/src# 

这说明有475个test app，只有12个没过，其他都过了。


总结：你对你的测试结果还不够了解。

**Comment by GCYYfun** [comment]
> 很好，改的很快！基于你新的信息，我重现了你的工作，得到类似的结果。
> 
> ```
> localhost:~/libc-test# make |grep FAIL|wc
>        12        50       597
> localhost:~/libc-test# 
> ```
> 
> 这说明有12个test没有通过，出错了，具体显示内容与你的信息一致。
> 
> ```
> localhost:~/libc-test/src# find . -name "*.exe"|wc
>       475       475     12829
> localhost:~/libc-test/src# 
> ```
> 
> 这说明有475个test app，只有12个没过，其他都过了。
> 
> 总结：你对你的测试结果还不够了解。

好、那应该是我对这个libc-test项目理解不够、不清楚其结构、对运行过程、输出结果、没有预期、基于现在的情况、我在去进一步了解、
